INSERT INTO libros (titulo, autor) VALUES 
-- De la primera foto (Primer plano)
('Fenomenología del espíritu', 'Georg Wilhelm Friedrich Hegel'),
('El pueblo duerme', 'Pepa Jiménez Pérez'),

-- De la segunda foto (Estantería principal)
('Yo, robot', 'Isaac Asimov'),
('Zombi: Guía de supervivencia', 'Max Brooks'),
('Une saison en enfer / Les Iluminations', 'Arthur Rimbaud'),
('Las moscas', 'Jean-Paul Sartre'),
('El castillo', 'Franz Kafka'),
('El misterio de la cripta embrujada', 'Eduardo Mendoza'),
('Los piratas del Halifax', 'Julio Verne'),
('De la Tierra a la Luna', 'Julio Verne'),
('Las bicicletas son para el verano', 'Fernando Fernán Gómez'),
('El fantasma de Canterville y otros cuentos', 'Oscar Wilde'),
('La genealogía de la moral', 'Friedrich Nietzsche'),
('El Anticristo', 'Friedrich Nietzsche'),
('El crepúsculo de los ídolos', 'Friedrich Nietzsche'),
('Demian', 'Hermann Hesse'),
('Lecturas para minutos', 'Hermann Hesse'),
('Bajo las ruedas', 'Hermann Hesse'),
('Los versos del Capitán', 'Pablo Neruda'),
('En el balneario', 'Hermann Hesse'),
('La hojarasca', 'Gabriel García Márquez'),
('Mi credo', 'Hermann Hesse'),
('Antología poética', 'Vicente Aleixandre'),
('El principito', 'Antoine de Saint-Exupéry'),
('Veinte poemas de amor y una canción desesperada', 'Pablo Neruda'),
('El bello verano', 'Cesare Pavese'),
('El arte de amar', 'Erich Fromm'),
('Temas de España', 'Miguel Hernández'),
('Poemes i cançons', 'Lluís Llach'),
('La insoportable levedad del ser', 'Milan Kundera'),
('Claros del bosque', 'María Zambrano'),
('Lenguaje, verdad y lógica', 'A. J. Ayer'),
('Anarquismo y sexualidad', 'Helena Andrés Granel'),
('Introducción a le estética', 'G.W.F Hegel'),
('Emakume olerkariak', 'Julia Otxoa'),

-- De la tercera foto (Libros tumbados y otros)
('Cafés con el diablo', 'Vicente Romero'),
('Problemas de Estadística para Ingenieros', 'Fernando Martínez Álvarez'),
('Álgebra Lineal con métodos elementales', 'Luis Merino / Evangelina Santos'),
('La teoría de la relatividad', 'Albert Einstein'),
('Coraline', 'Neil Gaiman'),
('Historia de la filosofía', 'Bertrand Russell'),
('Antología poética', 'Paul Verlaine'),
('Las flores del mal', 'Charles Baudelaire'),
('Kama Sutra (Antología poética)', 'Rubén Darío'),
('El amor es un perro del infierno', 'Charles Bukowski'),
('La metamorfosis', 'Franz Kafka'),
('La condena', 'Franz Kafka');